import { NextRequest, NextResponse } from "next/server";
import { getSupabaseAdminClient } from "@/lib/supabase/server";
import { CreateOrderPayload } from "@/types";

export const dynamic = "force-dynamic";

/**
 * POST /api/orders — create an order.
 *
 * Security: we recompute every line price from the `menu_items` table using the
 * submitted menu_item_id, so the client cannot tamper with prices. The total is
 * derived server-side. The order number is generated by the DB default
 * (sequence → "#101", "#102", …); UUIDs are never exposed to users.
 */
export async function POST(request: NextRequest) {
  let payload: CreateOrderPayload;
  try {
    payload = (await request.json()) as CreateOrderPayload;
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const name = payload.customer_name?.trim();
  const phone = payload.customer_phone?.trim();

  if (!name) {
    return NextResponse.json({ error: "Name is required" }, { status: 400 });
  }
  if (!phone || phone.replace(/\D/g, "").length < 10) {
    return NextResponse.json(
      { error: "A valid 10-digit mobile number is required" },
      { status: 400 }
    );
  }
  if (!Array.isArray(payload.items) || payload.items.length === 0) {
    return NextResponse.json({ error: "Cart is empty" }, { status: 400 });
  }

  const supabase = getSupabaseAdminClient();

  // Look up authoritative prices for every menu item in the cart.
  const menuItemIds = [...new Set(payload.items.map((i) => i.menu_item_id))];
  const { data: dbItems, error: lookupErr } = await supabase
    .from("menu_items")
    .select("id, name, price, secondary_price, secondary_label")
    .in("id", menuItemIds);

  if (lookupErr) {
    console.error("orders lookup:", lookupErr.message);
    return NextResponse.json(
      { error: "Could not validate cart items" },
      { status: 500 }
    );
  }

  const byId = new Map((dbItems ?? []).map((i) => [i.id, i]));

  // Build server-trusted order lines.
  const lines: {
    menu_item_id: string;
    name: string;
    unit_price: number;
    quantity: number;
    line_total: number;
    variant_label: string | null;
  }[] = [];

  for (const item of payload.items) {
    const db = byId.get(item.menu_item_id);
    if (!db) {
      return NextResponse.json(
        { error: `Unknown menu item in cart` },
        { status: 400 }
      );
    }
    const quantity = Math.max(1, Math.floor(Number(item.quantity) || 0));

    // Resolve price: if the submitted variant matches the DB secondary label,
    // use secondary_price; otherwise the base price.
    let unitPrice = Number(db.price);
    let variantLabel: string | null = null;
    if (
      item.variant_label &&
      db.secondary_label &&
      item.variant_label === db.secondary_label &&
      db.secondary_price != null
    ) {
      unitPrice = Number(db.secondary_price);
      variantLabel = db.secondary_label;
    }

    lines.push({
      menu_item_id: db.id,
      name: db.name,
      unit_price: unitPrice,
      quantity,
      line_total: Number((unitPrice * quantity).toFixed(2)),
      variant_label: variantLabel,
    });
  }

  const total = Number(
    lines.reduce((sum, l) => sum + l.line_total, 0).toFixed(2)
  );

  // Insert the order (display_order_number is auto-generated by the DB).
  const { data: order, error: orderErr } = await supabase
    .from("orders")
    .insert({
      customer_name: name,
      customer_phone: phone,
      total_amount: total,
      status: "NEW",
      note: payload.note ?? null,
    })
    .select("id, display_order_number, status, total_amount, created_at")
    .single();

  if (orderErr || !order) {
    console.error("orders insert:", orderErr?.message);
    return NextResponse.json(
      { error: "Failed to create order" },
      { status: 500 }
    );
  }

  // Insert the order items.
  const { error: itemsErr } = await supabase.from("order_items").insert(
    lines.map((l) => ({ ...l, order_id: order.id }))
  );

  if (itemsErr) {
    console.error("order_items insert:", itemsErr.message);
    // Roll back the order to avoid an order with no items.
    await supabase.from("orders").delete().eq("id", order.id);
    return NextResponse.json(
      { error: "Failed to save order items" },
      { status: 500 }
    );
  }

  return NextResponse.json({ order }, { status: 201 });
}
